name: os
base-image: ghcr.io/ublue-os/sericea-main
fedora-version: latest
description: Personal Fedora/OSTree image based on uBlue
scripts:
  # "Pre" scripts run very early in the build, immediately after your custom
  # repos have been imported (so that you can access those repos if necessary).
  pre:
  post:

rpm:
  repos:
    - https://copr.fedorainfracloud.org/coprs/alternateved/keyd/repo/fedora-%FEDORA_VERSION%/alternateved-keyd-fedora-%FEDORA_VERSION%.repo
  install:
    - libadwaita
    - fish
    - keyd
  remove:
    # Remove the native firefox (from Fedora) in favor of the Flatpak.
    - firefox
    - firefox-langpacks

firstboot:
  # just setup-flatpaks
  flatpaks:
    - org.mozilla.firefox
